### ISSUE TITLE
Prepare for v2.0.0

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#189]
We'd like to start preparing for an official 2.0.0 release and start adhering to strict [semantic versioning](https://semver.org). With 2.0.0, we'll likely want to clean up and deprecate anything that isn't considered "official" at this point. This could include:

- The legacy theme and all references to it
- Numbered color names, e.g. `blue0`
- Legacy icons and their source code

~~Since going to 1.0.0 would mean a **breaking** change, we've discussed renaming the package. This would ensure that anyone depending on the current `pcln-design-system` would not automatically get any breaking changes in their apps, and that upgrading to the new version would require some intentional changes to be made in dependencies and import statements.~~

~~We discussed this in our common components meeting, but would like to open up the discussion here for further input.~~

After releasing the 2.0.0 version, the intention is to **not** introduce any breaking changes for the foreseeable future, but only add functionality as needed. With that in mind, if there are any changes you would like to see happen in the design system, now is the time to discuss them.

**Update**: after a brief discussion, we feel like it would be better to keep the package name intact and bump the version to 2.0.0 to handle these changes

Work on this issue should be coordinated with the `next` branch, and PRs for the issues below should point to that branch.

- [x] Remove legacy theme and related props #238
- [x] Remove numbered color names and related warnings #239
- [x] Remove legacy SVG icons and related props #240
- [x] Remove default styles from Heading.h1 – Heading.h6 and update typographic styles #241
- [x] Loosen dependency versions and move styled-components to peerDependencies #242
- [x] Update to styled-system v2 #243

**Comment by hakimelek** [comment]
I would add that most of the components that could be designed as a compound component should have a set api to support that part of 1.0.0.

These components include: `Banner`, `Tag`, `Hug`, `InputField`,..

**Comment by jxnblk** [comment]
As discussed, the Tag and InputField components already use a compound component API, and updating the Banner and Hug components can be handled as non-breaking changes after 2.0.0
